### PR TITLE
Fixes and improvements for the ImGui overlay

### LINKED ISSUE #237: enable=1 + fps_limit draws overlay when no other extras are enabled
**Describe the bug**
When enable=1 and fps_limit under the [extras] section are enabled, but all other options are disabled, the overlay displays as a 32x32 box with no contents. It can still be toggled off with the overlay keybind at least.

**To Reproduce**
INI settings are:
[extras]
enable=1
fps_limit=90
fps_limit_inactive=0
show_fps=0
show_draw_count=0
show_fps_graph=0
show_timings=0
show_pso_compile_que=0
show_gc_que=0
overlay_toggle_key=78
fps_graph_max=80
fps_graph_min=0
fps_graph_w=512
fps_graph_h=256
enable_config_editor=0

on a fresh config.ini

1. Run game
2. Observe box in top-left of screen.

**Expected behavior**
The box should not display when there are no contents to display.

**Screenshots**
Annotation 2020-02-27 182739

**Additional context**
imgui.ini respects changes to the overlay position, but not its collapsed setting. The overlay can't be shrunken smaller than 32x32.

### PR DESCRIPTION
**Pull request by MTVirux**
- A default config editor window size has been added and a change to the spacing after the input field has been made. This removes the need to resize the window when opening it for the first time and makes it so that the window doesn't have to be set to an unecessary large width.

- Changed the enum name field of the Config Editor to be the same as the config line entry.

- Fixed #237  by putting the main window in a function behind a bool. The main window is rendered if any of it's "show" components are active. Along with this fix the possibility of the user acessing the config editor when the main window doesn't have to be rendered was added. Also attached to this change, the same conditional window flags from the main window were put on the config editor window

### CODE REVIEW

File: d912pxy/d912pxy_extras.cpp [hunk 1]
```diff
@@ -87,13 +89,17 @@ void d912pxy_extras::Init()
...
 		{
-			overlayShowMode = eoverlay_show;
+			bShowMainWindow = true;
 			break;
 		}
 	}
 
+	//Sets Config Editor window to visible if enabled when there's no need for the main window
+	if ((bShowMainWindow == false) && (bEnableConfigEditor == true))
+		bShowConfigEditor = true;
```
Comment (megai2) [inline d912pxy/d912pxy_extras.cpp]: then if you close editor window, there will be no way to open it back up, so it should be 
bShowMainWindow |= bEnableConfigEditor;

Comment (MTVirux) [reply d912pxy/d912pxy_extras.cpp]: Wouldn't that cause it to always start open even when the main window is present?
If the concern is the user closing the window when there's no main window the best approach I can think is a trenary operator on the window parameter.
